if ( GetLocale() == "ruRU" ) then

DugisLocals = {
PART_TEXT = "Односторонний",
	
--	
	["Dugi Guides"] = "Путеводитель Dugi", -- BINDING_HEADER_DUGI
	["Dugi Guides Off"] = "Путеводитель Dugi отключен",
	["Dugi Guides On"] = "Путеводитель Dugi включен",
	["|cff11ff11Dugi Guides: |rNew character detected. Wiping settings."] = "|cff11ff11Путеводитель Dugi: |rОбнаружен новый персонаж. Стирание настроек.",
	["Auto Track Local Quest"] = "Автоматически отслеживать локальные задания",
	["Automatically remove non-local (not in current map) quest and track local quest to the objective tracker. This will trigger when you accept a quest or during a zone change event"] = "Автоматически удалять нелокальные (не на текущей карте) задания и отслеживать локальные задания в списке целей. Это сработает, когда вы примете задание или во время смены локации",
	["Auto Loot Quest Item"] = "Автоматически выбирать награды за задания",
	["Abandon Quests Button"] = "Кнопка отмены заданий",
	["Mass abandon quests button in your quest log to automatically abandon all quests by their category or zone"]= "Кнопка массового отказа от заданий в вашем журнале, необходима для автоматической отмены всех заданий по их категории или зоне",
	["Auto Select Flight Path"] = "Автоматически выбирать маршруты полетов",
	["Automatically select the suggested flight path after opening the flightmaster map"] = "После открытия карты мастера полетов автоматически выбирать предложенный маршрут полета.",
	["Use Taxi System"] = "Использовать транспортную систему",
	["Taxi system will find the fastest route to get to your destination with the use of portals, teleports, vehicles etc. Disabling this option will give you a direct waypoint instead."] = "Транспортная система найдет самый быстрый маршрут, чтобы добраться до пункта назначения с использованием порталов, телепортов, транспортных средств и т.п. Отключение этого параметра даст прямую путевую точку.",
	["Bronze"] = "Бронза",
	["Okay"] = "Ок",
	["Cancel"] = "Отмена",
	["Weapon Preference"] = "Предпочтение оружия",
	["Choose how gear advisor will decide which weapon to equip in the main hand and off hand slot when dual wielding. Auto option will decide based on the class and spec."] = "При использовании парного оружия выберите, какое оружие рекомендовать для основной руки.",
	["Auto"] = "Авто",
	["Fast / Slow"] = "Быстро / Медленно",
	["Slow / Fast"] = "Медленно / быстро",
	["Never Swap"] = "Не менять местами",
	["Suggest Trinkets"] = "Рекомендовать аксессуары",
	["A trinket is scored by its stats and item level but not the 'use' or special effect which can make the trinket suggestion inaccurate.\n\nUnticking this setting will disable the trinkets suggestion."] = "Ювелирные изделия оцениваются по атрибутам и оценкам, а не по специальным эффектам, которые используются или срабатывают, поэтому совет ювелирных изделий не так точен.\n\nОтключение этого параметра отключит предложение аксессуаров.",
	["Display All Stats"] = "Показать все свойства",
	["Display unused stats for gear scoring"] = "Отображает атрибуты, которые не используются при подсчете оценки.",
	["Reset Scores"] = "Сбросить оценки",
	
	-- GearAdvisor.lua
	["Agility"] = "Ловкость",
	["Attack Power"] = "Сила атаки",
	["Armor"] = "Броня",
	["Bonus Armor"] = "Бонус брони",
	["Avoidance"] = "Уклонение",
	["DPS"] = "УВС",
	["DPS - Main"] = "УВС - Осн.",
	["DPS - Off"] = "УВС - Втр.",
	["Intellect"] = "Интеллект",
	["Leech"] = "Высасывание",
	["Mastery"] = "Искусность",
	["Critical Rating"] = "Рейтинг крит. удара",
	["Haste Rating"] = "Рейтинг скорости",
	["Multistrike"] = "Множественный удар",
	["Spell Power"] = "Сила заклинаний",
	["Spirit"] = "Дух",
	["Stamina"] = "Выносливость",
	["Strength"] = "Сила",
	["Versatility"] = "Многофункциональность",
	["XP Bonus"] = "Бонус опыта",
	["Gear Upgrade Suggested"] = "Рекомендуемая экипировка",
	
	
	-- arrow.lua
	["Waypoint arrow not available. Click here to check the world map"] = "Невозможно использовать направляющую стрелку. Нажмите, чтобы посмотреть карту мира",
	["Waypoint reached."] = "Точка достигнута.",
	[" mil"] = " миль",
	[" yd"] = " ярдов",
	[" km"] = " км",
	[" m"] = " м",
	[" (World Quest)"] = " (Мировое задание)",	
	["Dugi Arrow"] = "Стрелка Dugi",
	["Remove Waypoint"] = "Удалить точку",
	["Remove All Waypoints"] = "Удалить все точки",
	["Refresh"] = "Обновить",
	["Waypoint is on a different floor"] = "Путевая точка на другом этаже",
	["Lock Arrow"] = "Блокировать стрелку",
	["Unlock Arrow"] = "Разблокировать стрелку",
	["Arrow Scale"] = "Размер стрелки",
	["Lock Zone Map"] = "Блокировать карту",
	["Unlock Zone Map"] = "Разблокировать карту",
	["Text Scale"] = "Размер текста",
	
	-- Libs\menu.lua
	["Close Menu"] = "Закрыть меню",
	
	-- WorldMapTracking.lua
	["Remove tracking"] = "Отменить отслеживание",
	["Abandon All Quests?"] = "Вы уверены, что хотите отказаться от всех заданий?",
	["Yes"] = "Да",
	["No"] = "Нет",
	["Abandon All "] = "Отменить все '",
	[" Quests?"] = "' Задания?",
	["|cfff0eb20Flight location not learned|r"] = "|cfff0eb20Этот маршрут еще не изучен|r",
	
	-- TaxiDB.lua
	["DG: Flight master data updated!"] = "DG: Обновлены маршруты перелетов!",
	
	-- MapOverlays.lua 
	["|cffffd200Player:|r ---"] = "|cffffd200Игрок:|r ---",
	["|cffffd200Player:|r %s"] = "|cffffd200Игрок:|r %s",
	["|cffffd200Cursor:|r ---"] = "|cffffd200Курсор:|r ---",
	["|cffffd200Cursor:|r %s"] = "|cffffd200Курсор:|r %s",
	-- 座標改為 150 和 -150
	
	-- DugisGuideViewer.xml
	["Show / Hide Model Viewer"] = "Показать/скрыть предпросмотр моделей",
	["Preload"] = "Предзагрузка",
	["Reset Ban List"] = "Сбросить игнорируемые",
	["Go"] = "Идите",
	["Complete"] = "Завершить",
	["Not Now"] = "Не сейчас",
	
	
	-- DugisGuideViewer.lua
	["|cff11ff11" .. "Dugi: Disabled WorldQuestTracker's \"Auto World Map\" option, this needs to be off for Dugi waypoint."] = "|cff11ff11" .. "Dugi: Отключена опция WorldQuestTracker \"Auto World Map \", эта опция должна быть отключена для путевой точки Dugi.",
	["|cff11ff11/dugi way xx xx - |rPlace waypoint in current zone."] = "|cff11ff11/dugi way xx xx - |rУстановить путевую точку",
	["|cff11ff11/dugi fix - |rReset all Saved Variable setting."] = "|cff11ff11/dugi fix - |rСбросить значения всех переменных",
	["|cff11ff11/dugi reset - |rReset all frame position."] = "|cff11ff11/dugi reset - |rСбросить позиции всех окон",
	["|cff11ff11/dugi on - |rEnable Dugi Addon."] = "|cff11ff11/dugi on - |rВключить Dugi",
	["|cff11ff11/dugi off - |rDisable Dugi Addon."] = "|cff11ff11/dugi off - |rОтключить Dugi",
	["|cff11ff11/dugi config - |rDisplay settings menu."] = "|cff11ff11/dugi config - |rПараметры",
	["|cff11ff11/dugi automount - |rToogle Auto Mount on/off."] = "|cff11ff11/dugi automount - |rВключить/отключить автосредство передвижения",
	["|cff11ff11" .. "Dugi: Frame Reset"] = "|cff11ff11" .. "Dugi: Положение окна сброшено",
	["|cff11ff11" .. "Dugi: Cleared Saved Variables"] = "|cff11ff11" .. "Dugi: Очищенные сохраненные переменные",
	["|cff11ff11" .. "Dugi Guides Essential Mode"] = "|cff11ff11" .. "Основной режим Dugi",
	["|cff11ff11" .. "Dugi Guides Off"] = "|cff11ff11" .. "Отключить путеводитель Dugi",
	["|cff11ff11" .. "Dugi Guides On"] = "|cff11ff11" .. "Включить путеводитель Dugi",
	["|cff11ff11Auto Mount is ON|r"] = "|cff11ff11Вкл. автосредство передвижения|r",
	["|cff11ff11Auto Mount is OFF|r"] = "|cff11ff11Откл. автосредство передвижения|r",
	
		
	["Search Locations"] = "Искать место",
	["Locations in"] = "Расположен в",
	["Instance Portal"] = "Войдите в портал",
	["Portal "] = "Портал ",
	["Auto Quest Turn in"] = "Автоматически завершать задания",
	["Automatically turn in quests from NPCs. Disable with shift"] = "Автоматически завершать задания. Shift для отключения",
	["Automatically accept quests from NPCs. Disable with shift"] = "Автоматически принимать задания. Shift для отключения",
	["Loot Suggestion Priority"] = "Приоритет награды",
	
	["Blink Minimap Resource Nodes"] = "Мигающие точки на маленькой карте",
	["Resource nodes for gathering profession and battle pets will blink in your minimap to make it easier to notice"] = "На маленькой карте будут мигать точки сбора для профессий и боевых питомцев, чтобы их было легче найти.",
	["Resource nodes for gathering profession will blink in your minimap to make it easier to notice"] = "На маленькой карте будут мигать точки сбора для профессий и боевых питомцев, чтобы их было легче найти.",
	["Ignore Daily Quest Items"] = "Игнорировать предметы ежедневных заданий",
	["Don't suggest to replace quest items for completing daily quest"] = "Не рекомендуем заменять предметы, необходимые для ежедневного задания.",
	["Demon Hunter"] = "Охотник на демонов",
	["Waypoint Reached Sound"] = "Звук назначения",
	["Plays a ping sound upon reaching each waypoint"] = "Воспроизведите звук, когда вы дойдете до места назначения.",
	["Hide Model Preview in World Map"] = "Скрыть предпросмотр моделей возле карты мира",
	["|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tDisable suggestions if the highlighted\nsets are equipped:"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tОтключить предложения, если выделены\n　комплекты экипировки:",
	
	["Import Scores"] = "Импорт оценок",
	["Paste below scores from another addon and press Import."] = "Вставьте ниже оценки из другого дополнения и нажмите Импорт.",
	["Import"] = "Импорт",
	["Cancel"] = "Отмена",
	
	["Auto Mount"] = "Использовать автосредство передвижения",
	["Enable auto mount"] = "Включить автосредство передвижения",
	["Automatically mounts the fastest available mount."] = "Использовать самого быстрого.",
	["Prefered mount in flyable areas"] = "Предпочитать воздушных",
	["Prefered mount in non-flyable areas"] = "Предпочитать наземных",
	["Prefered mount in water"]  = "Предпочитать водоплавующих",
	["Key Bindings"] = "按鍵設定",
	["Delay After Spell (%.1f)"] = "Задержка после заклинания (%.1f)",
	["Don't mount"] = "Не использовать средство передвижения",
	["Random Favorite "] = "Случайный избранный",
	["Random Favorite"] = "Случайный избранный",
	["None"] = "Нет",
	["Ground"] = "Наземные",
	["Flying"] = "Летающие",
	["Aquatic"] = "Водоплавающие",
	
	["Enabled Map Preview"] = "Включить предпросмотр карты",
	["Addon"] = "Плагин",
	["Guide Mode"] = "Включить полную версию",
	["Essential Mode"] = "Базовый режим",
	["Off Mode"] = "Отключить",
	["Quick Settings"] = "Быстрая настройка",
	["Auto Mount"] = "Автосредство передвижения",
	["Gear Advisor"] = "Консультация по экипировке",
	["Auto Quest Accept/Turn in"] = "Автоматические задания",
	["Map Preview"] = "Предпросмотр карты",
	["Auto Select Flight Path"] = "Выбирать маршруты полетов",
	["Nameplates Tracking"] = "Отслеживание на индикаторах",
	["More settings.."] = "Дополнительные параметры...",
	["Home"] = "Домашняя",
	
	["Taxi System"] = "Транспортная система",
	["Use Zone Portals"] = "Использовать порталы в области",
	["Use Player Portals"] = "Использовать порталы игроков",
	["Use Boats"] = "Использовать лодку",
	["Use Class Portals"] = "Использовать порталы класса",
	["Use Flight Master Whistle"] = "Используйте свисток мастера полетов",
	
	["Dugi Arrow Colors"] = "Цвет стрелки Dugi",
	["Default Colors"] = "Цвет по умолчанию",
	["Bad Color"] = "Плохой цвет",
	["Middle Color"] = "Цвет в процессе",
	["Good Color"] = "Хороший цвет",
	["Exact Color"] = "Точный цвет",
	["Questing Area Color"] = "Цвет области заданий",
	["Notifications"] = "Уведомления",
	["Gear Advisor Suggestions as Notifications"] = "Уведомлять о рекомендациях экипировки",
	["If disabled standard gear suggestion prompts will be shown."] = "Если этот параметр отключен, отображается стандартная подсказка с рекомендациями экипировки.",
	["Large Frame Background"] = "Фон большого окна",
	["Ant Trail"] = "Муравьиный путь",
	["Dotted"] = "Точки",
	["Solid"] = "Линия",
	
	["Dugi Zone Map"] = "Dugi карта области",
	["Enable Zone Map"] = "Включить карту области",
	["Turn on / off the Dugi Zone Map feature"] = "Включает / выключает функцию карты области",
	["Enable Auto Zoom"] = "Включить автоматическое масштабирование",
	["Automatically Zoom in / out the map based on the current waypoint"] = "Автоматическое увеличение / уменьшение масштаба в зависимости от текущего маршрута.",
	["Show Quests POI"] = "Показать индикатор задания",
	["Turn on /off the point of interest icons for quests on the map"] = "Включает / выключает значок тега задания на карте",
	["Auto Hide Zone Map"] = "Автоматически скрывать карту области",
	["Automatically hides Dugi Map in case there are no waypoints."] = "Автоматически скрывать карту области, если нет путевых точек.",
	["Merge With Dugi Arrow"] = "Объединить со стрелкой Dugi",
	["Dugi Arrow text is displayed underneath the Zone Map and Dugi arrow is automatically shown within close range of the waypoints"] = "Текст стрелки Dugi появится под картой местности, а стрелка Dugi станет меньше и будет автоматически появляться на карте местности рядом с указанным маршрутом.",
	["Minimap Terrain Detail"] = "Маленькая карта местности",
	["Turns minimap terrain details on."] = "Включить детализацию местности на миникарте.",
	["Zone Map Border Opacity (%.1f)"] = "Прозрачность границы карты области (%.1f)",
	["Zone Map Opacity (%.1f)"] = "Прозрачность карты области (%.1f)",
	["Zone Map Size (%.1f)"] = "Размер карты области (%.1f)",
	["Character Arrow Size (%.1f)"] = "Размер стрелки (%.1f)",
	["Zone Map Border"] = "Граница карты области",
	["TextPanel"] = "Текстовая панель",
	["Default Setting"] = "Значение по умолчанию",
	["Dual Wield Preference"] = "Предпочитать парное оружие",
	
	["Void Elf Male"] = "Мужчина эльф бездны",
	["Void Elf Female"] = "Женщина эльф бездны",
	["Highmountain Tauren Male"] = "Мужчина таурен крутогорья",
	["Highmountain Tauren Female"] = "Женщина таурен крутогорья",
	["Lightforged Draenei Male"] = "Мужчина озаренный дреней",
	["Lightforged Draenei Female"] = "Женщина озаренный дреней",
	["Nightborne Male"] = "Мужчина ночной эльф",
	["Nightborne Female"] = "Женщина ночной эльф",

	["|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tNameplates Tracking"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tОтслеживание на индикаторе",
	["Show icon"] = "Показать иконку",
	["Show text"] = "Показать текст",
	["|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tNameplate icon size (%.1f)"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tРазмер иконки индикатора (%.1f)",
	["|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tNameplate text size (%.1f)"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tРазмер текста индикатора (%.1f)",
	


---
  ["|TInterface\\AddOns\\DugisGuideViewerZ\\Artwork\\UpgradeArrow:0|t|cff1eff00+%d%%|r upgrade over %s with %s"] = "|TInterface\\AddOns\\DugisGuideViewerZ\\Artwork\\UpgradeArrow:0|t|cff1eff00+%d%%|r лучше %s вместе %s",
  ["|TInterface\\AddOns\\DugisGuideViewerZ\\Artwork\\UpgradeArrow:0|t|cff1eff00+%d%%|r upgrade over %s"] = "|TInterface\\AddOns\\DugisGuideViewerZ\\Artwork\\UpgradeArrow:0|t|cff1eff00+%d%%|r лучше %s",
	["%s Portal in %s"] = "%s телепортируйтесь в %s",
  ["%s %s in %s"] = "%s %s в %s",
  ["([^%s]+) Trainer"] = "([^%s]+) Тренер",
  ["([^%s]+) Trainer Female"] = "女([^%s]+)Женщина тренер",
  ["|cff11ff11Dugi Guides: |rGrey quality items sold for %s"] = "|cff11ff11Путеводитель Dugi: |rПродан хлам за %s",
  ["|cff11ff11Dugi Guides: |rGear automatically repaired%s for %s"] = "|cff11ff11Путеводитель Dugi: |rЭкипировка автоматически отремонтирована%s，за %s",
  ["+2 (Heroic Dungeon)"] = "+2 (Героическое подземелье)",
  ["+3 (Raid)"] = "+3 (Рейд)",
  
--Aa
  ["Auto Tooltip (%.1fs)"] = "Автоматическая подсказка (%.1fs)",
  ["Allow NPC Journal to float anywhere on the screen"] = "Разрешить размещение журнала NPC в любом месте экрана",
  ["Auto quest accept feature will only accept quests in current guide"] = "Функция автоматического принятия задания будет принимать задания только текущего путеводителя.",
  ["Add waypoint"] = "Добавить путевую точку",
  ["Add %s to ban list"] = "Игнорировать %s",
  ["Archaeology"] = "Археология",
  ["Automatically repair all damaged equipment at repair NPC"] = "Автоматически ремонтировать экипировку у специальных NPC",
  ["Auto Repair"] = "Автоматический ремонт",
  ["Automatically maintain the best item for each slot as player level, active spec and inventory changes occur."] = "Автоматически поддерживать лучший предмет для каждого слота по мере изменения уровня игрока, активных характеристик и инвентаря.",
  ["Auto Equip Smart Set"] = "Автоматическая экипировка",
  ["Allow movement of the watch frame, not available if other incompatible addons are loaded."] = "Разрешить перемещение рамки часов, недоступно, если загружены другие несовместимые дополнения.", 
  ["Add a border for the Objective Tracker Frame"] = "Добавить рамку к окну списка целей задания.",
  ["Active Talent Specialization"] = "Текущая специализация",
  ["Add"] = "Добавить",  
	["Account Wide Achievement"] = "Общее достижение учетной записи",
	["Add minimap tracking icons on the world map."] = "Добавить значок отслеживания на карту мира.",
	["Alchemy"] = "Алхимия",
	["All Available Quests"] = "Все доступные задания",
	["All Tracked Quests"] = "Все отслеживаемые задания",
	["Allow a fixed Anchored Small Frame that will integrate with the Objective Tracker"] = "Разрешить фиксацию малого окна с интерацией его в окно целей задания",
	["Allow status frame to show all currently relevant quests."] = "Позволяет использовать окно состояния для отображения всех текущих заданий.",
	["Allows model viewer to function"] = "Разрешить просмотрщик моделей",
	["Alternative Leveling Guides:"] = "Альтернативное руководство:",
	["Always"] = "Всегда",
	["Amount of time the Map Preview should remain in view (zero to disable).  Enabling this feature will automatically set the world map to windowed mode on reload."] = "Когда отображается предварительный просмотр карты (0 означает отключение), включение этой функции автоматически переведет карту мира в режим окна при перезагрузке.",
	["Anchored Small Frame"] = "Закрепить малое окно",
	["Ant Trail Color"] = "Цвет муравьиного следа",
	["Apply Memory Settings"] = "Применить параметры памяти",
	["Apply"] = "Применить",
	["Auto"] = "Авто",
	["Automatic Quest Matching"] = "Автоматическая координация заданий",
	["Auto Quest Accept"] = "Автоматически принимать задания",
	["Auto Quest Item Loot"] = "Автоматически выбирать награды за задания",
	["Auto Sell Greys"] = "Автоматически продавать мусор",
	["Auto Stick"] = "Автоматически собирать стопки",
	["Automatic Waypoints"] = "Автоматические путевые точки", 
	["Automatically accept and turn in quests from NPCs. Disable with shift"] = "Автоматически принимать и завершать задания. Нажмите Shift, чтобы временно отключить",
	["Automatically loot quest items."] = "Автоматически собирать добычу.",
	["Automatically map waypoints from the Small Frame or from the Objective Tracker in essential mode"] = "Автоматически объединять путевые точки в малом окне или списка целей задания в базовом режиме",
	["Automatically sell grey quality items to merchant NPCs"] = "Автоматически продавать предметы низкого качества торговцам",

--Bb
  ["Battlemaster"] = "Военачальник",
  ["Banker"] = "Банкир",
  ["Best in slot - |c%s%s|r"] = "Лучший в слоте - |c%s%s|r",
  ["Best in slot with %s - |c%s%s|r"] = "Лучший в слоте с %s - |c%s%s|r",
	["Bell Toll Alliance"] = "Удар гонга альянс",
	["Bell Toll Horde"] = "Удар гонга орда",
	["BlackGold"] = "Черное золото",
	["Blacksmithing"] = "Кузнечное дело",
	["BloodElf Female"] = "Женщина крповавый эльф",
	["BloodElf Male"] = "Мужчина кровавый эльф",
	["Boat Docked"] = "Лодка пристыкована",
	["Boat to"] = "Плывите в",
	["Borders"] = "Рамки",
	["Bottom Left"] = "Внизу слева",
	["Bottom Right"] = "Внизу справа",
	["Bottom"] = "Внизу",
	["Bronce"] = "Бронза",
--Cc
  ["Collected"] = "Собранный",
  ["Class Trainer"] = "Классовый тренер",
  ["Class"] = "Класс", 
	["Classic Arrow"] = "Классическая стрелка",
	["Clear"] = "Очистить",	
	["Collect Garbage"] = "Сбор мусора",
	["Collect"] = "Собрать",
	["Buy Item"] = "Купить предмет",
	["Color Code Quest"] = "Цвет задания",
	["Color code quest against your character's level"] = "Сравнить цвет уровня задания с вашим уровнем",
	["Cooking"] = "Кулинария",	
	["Copy From"] = "Копировать из",
	["Current Guide"] = "Текущее",
	["Customize Macro"] = "Пользовательский макрос",
	["Customize Target Macro"] = "Пользовательский макрос цели",
--Dd
  ["Determines how gear should be scored, in order of greatest to least importance."] = "Определяет, как следует оценивать снаряжение в порядке наибольшего или наименьшего значения.",
  ["Duration (%.1fs)"] = "Длительность (%.1fс)",
  ["Disable Blizzard's Automatic Quest Tracking feature and use Dugi Automatic Quest Matching feature which will sync your Objective tracker with the current guide"] = "Отключить встроенное отслеживание заданий и использовать автоматическое отслеживание заданий Dugi",
  ["Dugi Smart Set"] = "Dugi экипировка",
  ["Do above for remaining %d items"] = "Остальные %d предметов такие же",
  ["Determines which scoring configuration should be used to equip gear with Dugi Smart Set."] = "Определяет, какую конфигурацию подсчета параметров следует использовать для автоматической экипировки Dugi.",
  ["Don't suggest to replace items with +cooking stats if equipped"] = "Не предлагать замену предметов, с бонусом + к кулинарии",
  ["Don't suggest to replace fishing pole or items with +fishing stats if equipped"] = "Не предлагать замену удочек или предметов, с бонусом + к рыбной ловле",
  ["Display a prompt to verify before committing auto equip changes"] = "Автоматически отображать напоминание перед экипировкой новых предметов",
  ["Druid"] = "Друид",
  ["Deathknight"] = "Рыцарь смерти",
	["DarkWood"] = "Черное дерево",
	["Default"] = "По умолчанию",
	["Delete a Profile"] = "Удалить профиль",
	["Detects account wide achievements completion."] = "Обнаруживать завершение достижений на учетной записи.",
	["Display ant trail between waypoints on the world map"] = "Отображать муравьиный след на карте мира",
	["Display Quest Level"] = "Отображать уровень задания",
	["Display quest objectives in status frame."] = "Объект задания отображается в окне статуса.",
	["Displays tooltip information under guide step"] = "Отображать подсказку под указателем шага",
	["Display"] = "Внешний вид",
	["Draenei Female"] = "Женщина дреней",
	["Draenei Male"] = "Мужчина дреней",
	["Dungeon Guides"] = "Путеводитель по подземельям",
	["Dwarf Female"] = "Женщина дворф",
	["Dwarf Male"] = "Мужчина дворф",
--Ee
  ["Equip recommended item:"] = "Надеть рекомендуемый предмет:",
  ["Enabling these Dugi Guides features will require the UI to reload.  Do this now?"] = "Включение этого параметра Dugi потребует перезагрузки интерфейса?",
  ["Expand in Both Directions"] = "Расширять в обе стороны",
  ["Expand Up"] = "Увеличить",
  ["Expand Down"] = "Уменьшить",
  ["Explosion"] = "Взрыв",
  ["Eternium"] = "Этерниум",
  ["ElvUI"] = "ElvUI",
  ["Enable NPC Journal Frame"] = "Включить окно журнала NPC",
  ["Enable Essentials"] = "Включить основы",
  ["Equip Set"] = "Выбор экипировки",
  ["Enable /way commands and compatibility with other addons that use TomTom addon (eg LightHeaded)"] = "Включить команду /way для совместимости с другими планинами, использующими TomTom (Например：LightHeaded).",
  ["Enable user placed waypoints on the world map by pressing Ctrl + Right click or Shift + Right click to link them together, disable this option if the hotkey conflict with another addon"] = "Нажмите Ctrl + Вправо или Shift + Вправо на маленькой карте, чтобы включить отображение маршрута. Если существуют конфликты с ярлыками других плагинов, отключите эту опцию.",
	["Easy"] = "Легко",
	["Embedded Tooltip"] = "Встроенная подсказка",
	["Enable Sticky Frame"] = "Включить липкие окна",
	["Enchanting"] = "Зачарование",
	["Engineering"] = "Инженерное дело",
	["Existing Profiles"] = "Существующие профили",
--Ff
  ["Floating NPC Journal Button"] = "Плавающая кнопка журнала NPC",
	["Find Nearest"] = "Поиск ближайшего",
	["First Aid"] = "Первая помощь",	
	["Fishing"] = "Рыбная ловля",	
	["Fixed Width Small Frame"] = "Рамка фиксированной ширины малого окна",
	["Flash"] = "Вспышка",  
	["Floating Item Button"] = "Плавующая кнопка предмета",
	["Floating Small Frame won't adjust size horizontally and remain the same width as the Objective Tracker."] = "Маленькая рамка, которую можно свободно перемещать, имеет ту же ширину, что и окно целей. Горизонтальный размер не может быть изменен.",
	["Fly to"] = "Летите в",
	["Frames"] = "Окна",
--Gg
  ["Gold"] = "Золото",
  ["Guide step text color intensifies when moused over"] = "Улучшать цвет текста текущего шага путеводителя при наведении курсора мыши.",
  ["Guide Suggest Mode"] = "Режим предложения путеводителя",
  ["Gear Set"] = "Выбор экипировки",
  ["Gear Scoring"] = "Рейтинг экипировки",
  ["General Task"] = "Основная задача",
	["Gnome Female"] = "Женщина гном",
	["Gnome Male"] = "Мужчина гном",
	["Goblin Female"] = "Женщина гоблин",
	["Goblin Male"] = "Мужчина гоблин",
	["Go"] = "Идите",
	["Gray"] = "Серый",
	["Green"] = "Зеленый",
	["Guide Suggest Mode"] = "Режим предложения путеводителя",
--Hh
  ["Humm"] = "Хмм",
  ["Highlight Guide Steps"] = "Выделить шаги путеводителя",
  ["Hearth to"] = "Телепортируйтесь в",
  ["Hunter"] = "Охотник",
  ["Highest Vendor Price"] = "Самая высокая цена продавца",
  ["Hard"] = "Сложно",
	["Herbalism"] = "Сбор трав",	
	["Hide Border"] = "Скрыть границу",
	["Hides the minimized map border when map preview is on."] = "Когда предварительный просмотр карты включен, скрыть свернутую границу карты.",
	["High"] = "Высокая",
	["Human Female"] = "Женщина",
	["Human Male"] = "Мужчина",
--Ii
  ["Item Button Size (%.1f)"] = "Размер кнопки предмета (%.1f)",
  ["Item has the following stats:"] = "Предмет имеет следующие параметры:",
  ["Ignore Cooking Items"] = "Игнорировать кулинарные предметы",
  ["Ignore Fishing Items"] = "Игнорировать предметы рыбалки",
  ["Inactive Talent Specialization"] = "Специализация не включена",
	["Increases the width of the Objective tracker"] = "Увеличить ширину окна отслеживания",
	["Inscription"] = "Начертание",	
--Jj
	["Jewelcrafting"] = "Ювелирное дело",	
--Ll
  ["Lock model viewer frame into place"] = "Закрепить на месте окно модели",
  ["Lock Model Frame"] = "Закрепить окно модели",
  ["Lock the objective tracker frame."] = "Закрепить окно отслеживания",
  ["Lock Objective Tracker"] = "Закрепить окно отслеживания",
	["Leatherworking"] = "Кожевничество",
	["Left"] = "Слева",
	["Leveling Mode"] = "Режим прокачки",
	["Lock large frame into place"] = "Закрепить на месте большое окно",
	["Lock Large Frame"] = "Закрепить большое окно",
	["Lock small frame into place"] = "Закрепить на месте малое окно",
	["Lock Small Frame"] = "Закрепить малое окно",
	["Low"] = "Низкий",
--Mm
  ["Multi-step - Anchored"] = "Несколько шагов - Закрепленный",
  ["Multi-step"] = "Несколько шагов",
  ["Minimal"] = "Минимум",
  ["Map Ping"] = "Задержка карты",
  ["My Corpse"] = "Моё тело",
  ["Move Objective Tracker"] = "Переместить окно отслеживания",
  ["Manual Waypoints"] = "Ключевые точки вручную",
  ["Mage"] = "Маг",
  ["Monk"] = "Манах",
  ["Manual Mode"] = "Ручной режим",
	["Map Coordinates"] = "Координаты карты",
	["Map Preview"] = "Карта предварительного просмотра",
	["Maps"] = "Карты",
	["Memory"] = "Память",
	["Metal"] = "Металл",
	["MetalRust"] = "Ржавчина",
	["Minimal - No Borders"] = "Минимальное - Без границы",
	["Minimap Blob Quality"] = "Качество капли на миникарте",
	["Mining"] = "Горное дело",
	["Model Database"] = "База данных моделей",
	["Multiple Step Mode"] = "Многошаговый режим",
--Nn
  ["NPC Journal Button Size (%.1f)"] = "Размер кнопки журнала NPC (%.1f)",
  ["NPC Journal Button"] = "Кнопка журнала NPC",
  ["Not Collected"] = "Не собрано",
  ["No"] = "Нет",
  ["Never"] = "Никогда",
	["New Profile"] = "Новый профиль",
	["NightElf Female"] = "Женщина ночной эльф",
	["NightElf Male"] = "Мужчина ночной эльф",
	["None"] = "Нет",
	["Normal"] = "Обычный",
	["Not Now"] = "Не сейчас",
	["NPC Name Database"] = "База данных имен NPC",
--Oo
  ["Only Quests In Current Guide"] = "Только задания из текущего путеводителя",
  ["Or leave slot empty:"] = "Или оставьте ячейку постой:",
  ["Or keep equipped item:"] = "Или сохраните экипированный:",
  ["OK"] = "ОК",
  ["Objective Tracker Frame Border"] = "Граница окна отслеживания",
	["OnePixel"] = "1 пиксель",
	["OR complete Quests in Log first"] = "ИЛИ сначала выполните задания из журнала заданий",
	["Orc Female"] = "Женщина орк",
	["Orc Male"] = "Мужчина орк",
	["Other"] = "Другое",
--Pp
  ["Player/Target level difference. Used in determining caps for hit and expertise."] = "Разница в уровне игрока/цели. Используется при определении ограничений для попадания и получения опыта.",
  ["Priest"] = "Жрец",
  ["Paladin"] = "Паладин",
	["Pandaren Female"] = "Женщина пандарен",
	["Pandaren Male"] = "Мужчина пандарен",
	["Preload"] = "Предварительная загрузка",
	["Preview Quest Objectives"] = "Предварительный просмотр целей задания",
	["Profiles"] = "Профили",
	["Provides localized NPC names. Required for target button."] = "Отображать локализованные имена NPC. Необходимо включить кнопку цели.",
--Qq
  ["Quest Objectives"] = "Цели задания", 
	["Quest Complete Sound"] = "Звук завершения задания",
	["Quest Level Database"] = "База данных уровней заданий",
	["Questing"] = "Выполнение заданий",	
--Rr
  ["Relative to Watch Frame"] = "Относительно окна отслеживания",
  ["Remove %s Tracking"] = "Отменить отслеживание %s",
  ["Reset Ban List"] = "Сбросить игнорируемые",
  ["Rogue"] = "Разбойник",
  ["Reset weights"] = "Сбросить вес",
	["Recommended Preset Settings"] = "Рекомендуемые предустановленные настройки",
	["Red"] = "Красный",
	["Reload"] = "Перезагрузить",
	["Remove Map Fog"] = "Показать неисследованную область",
	["Reset Frames Position"] = "Сбросить позицию окна",
	["Reset Profile"] = "Сбросить профиль",
	["Reset"] = "Сбросить",
	["Riding"] = "Верховая езда",
	["Right"] = "Справа",
--Ss
  ["Size of the target button."] = "Размер кнопки цели",
  ["Size of the item button."] = "Размер кнопки объекта задания",
  ["Small Frame Font Size (%.1f)"] = "Размер шрифта малого окна (%.1f)",
  ["Small Frame Behavior"] = "Поведение малого окна",
  ["Standard - Anchored"] = "Стандартный - Закрепленный",
  ["Standard"] = "Стандартный",
  ["Simon Chime"] = "Simon Chime",
  ["Shing!"] = "Shing!",
  ["Stat Cap Level Difference"] = "Статистическая разница уровней",
  ["Show step descriptions in the Sticky Frame"] = "Показать пошаговые инструкции в липком окне",
  ["Sticky Frame Step Description"] = "Вставить описание окна шага",
  ["Suggest guides for your player on level up"] = "Советовать оптимальный путеводитель при получении нового уровня игроком",
  ["Set Tracking Filters..."] = "Установить фильтр отслеживания...",
  ["Set as waypoint"] = "Установить путевую точку",
  ["Smart Gear Set"] = "Улучшение экипировки",
  ["Show Auto Equip Prompt"] = "Предлагать улучшение элементов экипировки",
  ["Shaman"] = "Шаман",
  ["Specialization"] = "Специализация",
	["Scroll"] = "Прокрутить",
	["Shift click a quest step to track in the frame"] = "Удерживая нажатой клавишу «Shift», нажмите на шаг задания для его отслеживания",
	["Short Circuit"] = "Короткое замыкание",
	["Show Ant Trail"] = "Отображать муравьиный след",
	["Show Corpse Arrow"] = "Отображать стрелку к телу",
	["Show destination coordinates in the status frame tooltip"] = "Отображать координаты конечной точки в окне подсказки",
	["Show Dugi Arrow"] = "Отображать Dugi-стрелку",
	["Show Dugis waypoint arrow"] = "Отображать путевую стрелку Dugi",
	["Show DG Icon Button"] = "Отображать DG-кнопку",
	["Show Player and Mouse coordinates at the bottom of the map."] = "Отображать координаты игрока и мыши под картой.",
	["Show Quest Objectives"] = "Отображать объекты задания",
	["Show target button frame"] = "Отображать форму с кнопкой цели",
	["Show Target Button"] = "Отображать кнопку цели",
	["Show the corpse arrow to direct you to your body"] = "Отображать стрелу, которая поможет вам найти свое тело.",
	["Show the On/Off button which enables or disables the guide"] = "Отображать кнопку-переключатель включения/отключения путеводителя",
	["Show the quest level on the large and small frames"] = "Отображать уровни задания в большом и маленьком окне",
	["Shows a small window to click when an item is needed for a quest"] = "Включить отображение маленького окна, с предметами, необходимыми для выполнения задания",
	["Shows minimum level required for quests"] = "Отображать минимальный требуемый уровень для выполнения задания.",
	["Single Quest"] = "Одиночная задание",
	["Skinning"] = "Внешний вид",	
	["Small Frame Border"] = "Граница маленького окна",
	["Small Frame Effect"] = "Эффект маленького окна",
	["Standard - Anchored"] = "Стандартный - Закрепленный",
	["Step Complete Sound"] = "Звук завершения шага",
	["Stone"] = "Камень",
	["StonePattern"] = "Камень стиль.",
	["Suggest guides for your player on level up"] = "Советовать оптимальный путеводитель при получении нового уровня игроком",
	["Switch between modern and classic arrow icons"] = "Переключайтесь между современными и классическими иконками стрелки.",
--Tt
  ["Tooltip"] = "Подсказка",
  ["Target Button Size (%.1f)"] = "Размер кнопки цели (%.1f)",
  ["This feature will automatically add 'as you go...' step into sticky frame"] = "Эта функция автоматически добавит шаг 'Когда вы доберетесь до…' в соответствующую структуру окна.",
  ["Take"] = "Получите",
  ["Talk to %s and fly to %s"] = "Поговорите с %s и летите в %s",
  ["Talk to %s to get flight master data."] = "Поговорите с %s, чтобы получить информацию о новых путях полетов.",
  ["TomTom Addon Emulation"] = "Имитация плагина TomTom",
	["Tailoring"] = "Портняжное дело",
	["Target Button"] = "Кропка цели",
	["Target the NPC needed for the quest step"] = "Выберите необходимого для задания NPC в качестве цели.",
	["Tauren Female"] = "Женщина таурен",
	["Tauren Male"] = "Мужчина таурен",
	["Thin"] = "Тонкий",
	["Title"] = "Заголовок",
	["Tooltip Anchor"] = "Якорь подсказки",
	["Tooltip Coordinates"] = "Координаты подсказки",
	["Top Left"] = "Сверху слева",
	["Top Right"] = "Сверху справа",
	["Top"] = "Сверху",
	["Track Achievements"] = "Отслеживать достижения",
	["Track Rare Creatures"] = "Отслеживать редких монстров",
	["Troll Female"] = "Женщина тролль",
	["Troll Male"] = "Мужчина тролль",
	["Turn in"] = "Завершить",
--Uu
  ["Use: Restores [%d/,/.]+ health"] = "Используйте: Восстановление [%d/,/.]+ здоровья",
  ["Use the LFG Teleport to %s"] = "Используйте телепорт системы поиска рейда в %s",
  ["Use"] = "Использовать",
  [" using guild bank"] = " используя средства банка гильдии",
  ["Use guild funds when repairing automatically"] = "Использовать средства банка гильдии для автоматического ремонта.",
  ["Use Guild Bank"] = "Использовать банк гильдии",
	["Undead Female"] = "Женщина нежить",
	["Undead Male"] = "Мужчина нежить",
	["Unload Modules"] = "Выгрузить модули",
	["Unloading modules will allow the addon to run on low memory setting in Essential Mode  but will require a UI reload to return back to normal. "] = "Выгрузка модуля заставит расширение работать в основном режиме с низкими требованиями к памяти, но перегрузка интерфейса вернет режим работы в нормальное состояние.",
	["Use Carbonite Arrow"] = "Использовать стрелку Carbonite",
	["Use Flightmasters"] = "Использовать менеджер полетов",
	["Use the Carbonite arrow instead of the built in arrow"] = "Использовать стрелку Carbonite вместо встроенной стрелки.",
	["Use the same border that is selected for the large frame"] = "Использовать туже рамку, что и у большого окна",
	["Use the TomTom arrow instead of the built in arrow"] = "Использовать стрелку TomTom вместо встроенной стрелки.",
	["Use TomTom Arrow"] = "Использовать TomTom стрелку",
--Vv
	["View undiscovered areas of the world map, type /reload in your chat box after change of settings"] = "Просматривать неоткрытые области карты мира /reload。",
--Ww
  ["Wham!"] = "Вхам!",
  ["Waypoint %d"] = "Путевая точка %d",
  ["Waypoint (%d+)"] = "Путевая точка (%d+)",
  ["Warlock"] = "Колдун",
  ["Warrior"] = "Воин",
	["Watch Frame Border"] = "Соблюдать границы окна",
	["Waypoints"] = "Ключевые точки",
	["War Drums"] = "Барабаны битвы войны",
	["Wider Objective Tracker"] = "Широкий список задач",
	["Window Close"] = "Закрыть окно",
	["Window Open"] = "Открыть окно",
	["Wood"] = "Дерево",
	["World Map Tracking"] = "Отслеживать карту мира",
	["Worgen Female"] = "Женщина оборотень",
	["Worgen Male"] = "Мужчина оборотень",
--Yy
  ["Yes"] = "Да",
	["Yellow"] = "Желтый",
	}
setmetatable(DugisLocals, {__index=function(t,k) rawset(t, k, k); return k; end})	
end